### ISSUE TITLE
Events seem to be caching even after changing users.

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-mobile-react#100]
Log in to the app as a Super Admin.
View the events. (There is a Draft event that should _only_ be available to super admins)
Log out
Create a new user
Log in
The event is still visible

**Comment by mrmaDrma** [comment]
Hey there,

I've tested this issue and it looks like api returns all events, including Draft events for users that are not super admins. 
Can someone from BE confirm this ?
@Krakaw  @Tas4tari @simple-taskic

**Comment by Krakaw** [comment]
The API does not return draft events to public users / users that are not a part of the organization.
Using a superuser account:
```
-> % curl -s -H "Authorization: Bearer ACCESS_KEY" https://staging.api.bigneon.com/events | jq | grep status | sort | uniq -c | sort -nr
  13       "status": "Published",
   4       "status": "Draft",
```
Using a guest account
```
-> % curl -s https://staging.api.bigneon.com/events | jq | grep status | sort | uniq -c | sort -nr
  13       "status": "Published",
```

**Comment by Krakaw** [comment]
@mrmaDrma I think the problem is here: https://github.com/big-neon/bn-mobile-react/blob/e0acf244785573fa0eaf860f176cdc46fed78795/src/state/authStateProvider.js#L62
When the user logs out, I don't think it is clearing the tokens correctly.
The `getAllKeys()` requires a callback, I don't think it returns a Promise. So If we change that line to 
```
    await AsyncStorage.getAllKeys(AsyncStorage.multiRemove)
```
it should fix the issue.
