### ISSUE TITLE
Link App CONTACT US button to Big Neon Support Center

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#102]
The Big Neon APP CONTACT US button is currently linked to a users email address.

It needs to be linked to or Help Desk Support Center instead

https://support.bigneon.com/hc/en-us/categories/360001444351-Fan-Support <https://support.bigneon.com/hc/en-us/categories/360001444351-Fan-Support>

**Comment by Tas4tari** [comment]
@mileTadic1994 Can you please have a look at this issue

**Comment by Tas4tari** [comment]
@mileTadic1994 has this been completed?

**Comment by Anziskavds** [comment]
Tested on Beta and is working as expected. When you click on Contact Support it directs you to your email with fansupport@bigneon.com email address already added. User cab just type a email and send it

**Comment by Anziskavds** [comment]
Tested Prod on Big Neon Android App and when I clicked Contact support I was redirected to my emails where the fan support email address was already added in on the email. Tested successful

**Comment by Tas4tari** [comment]
@Anziskavds This should direct you to the help desk support centre and not to an email, does it do this?
This is where it should redirect you to:
https://support.bigneon.com/hc/en-us/categories/360001444351-Fan-Support https://support.bigneon.com/hc/en-us/categories/360001444351-Fan-Support
