### ISSUE TITLE
Ticket Transfers - Cancel/Decline a Transfer in Transit

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#113]
Context: When a ticket transfer is created the transferred ticket immediately arrives in the Big Neon account of the transferee if the transfer address  (email/phone) exists in the system associated with a user. If the transfer address does not already exist in the system, or user enters the incorrect information. the ticket sits in a state of limbo until it's accepted or the transfer expires. In "limbo" the  information cannot be changed or canceled at the moment. This accounts for a large % of our customer support requests.

A user should be able to cancel a transfer until it has actually been accepted into a users wallet
If a user cancels the transfer
The ticket should return to the original transferrers account
A notification should be sent to the transferee to let them know the transfer was cancelled by the party who initiated it originally

Sender Cancel via Email lo-fi prototype:
Desktop: https://sketch.cloud/s/kLd5D/a/o0YjE5/play
Mobile: https://sketch.cloud/s/kLd5D/a/M0yZP3/play

Sender Cancel via mobile lo-fi prototype:
https://sketch.cloud/s/kLd5D/a/pladnp/play

Notification of Cancel:
Mobile: https://sketch.cloud/s/kLd5D/a/GGmMWw/play
Desktop: https://sketch.cloud/s/kLd5D/a/qkezOy/play

**Comment by Krakaw** [comment]
Here is the `Cancel` endpoint https://big-neon.github.io/bn-api-node/classes/_resources_transfers_.transfersresource.html#cancel

**Comment by Anziskavds** [comment]
Tested on Beta on Big Neon App and I found that when tickets have been transferred to an existing user, the existing user doesn't need to accept the ticket transfer before it shows in their Big Neon "My Events". This makes it impossible for the user who transferred the ticket to cancel the ticket transfer. @Krakaw @Tas4tari
