### ISSUE TITLE
Production Bug: Purchase: Validation error when carting 4-pack ticket type via app - for Mickey Lion TONIGHT

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#123]
Event: Mickey Lion <https://www.bigneon.com/admin/events/9f5d98c3-d7b6-45a2-8092-cd3622dd2e8e/dashboard> (Tonight)

Issue: Customers cannot purchase the FOUR PACK Ticket Type while using the Big Neon App

Steps to reproduce

1.Open Big Neon App (Not web)

2.Locate Mickey Lion <https://www.bigneon.com/events/mikey-lion-desert-hearts-j-phlip-dirtybird-gorje-hewek-izhevski-adid> Event

3. Select the FOUR PACK Ticket Type and you will get the Validation Error (Screenshot attached)

Please note that you can cart and purchase tickets for this event via Desktop/Web

**Comment by Tas4tari** [comment]
@mrmaDrma For checking ticket quantity, a few notes from @Krakaw :
The other part of this is also the increment and the limit per person 
So:
Check available >= limit_per_person
Check available >= increment
Set qty =  (increment > 2) ? increment : (2 > available) ? available : 2

**Comment by Tas4tari** [comment]
@mrmaDrma What is the progress on this

**Comment by Tas4tari** [comment]
@mrmaDrma What is the progress on this?

**Comment by Tas4tari** [comment]
@mrmaDrma What is the progress on this

**Comment by Tas4tari** [comment]
@mrmaDrma What is the progress on this

**Comment by mrmaDrma** [comment]
@Tas4tari I talked with @simple-taskic, he said he will look at this...
