### ISSUE TITLE
Create account - password validation

### ISSUE THREAD

**Issue by Mihajlo21** [big-neon/bn-mobile-react#125]
When User wants to create a new account, he is able to proceed to next step without populating password input field.

Steps to reproduce:

1) Start Big Neon app
2) Click on "Continue with email"
3) Click on "Create one"
4) Enter email address using valid data
5) Click on "Let's Do This"
6) Confirm that user is able to go to the next step without entering password

**Comment by Tas4tari** [comment]
@mrmaDrma Maybe you can have a look at this in the interim

**Comment by Tas4tari** [comment]
Tested in Prod, user is unable to proceed without entering a password as the "Let's do this" button is now greyed out
