### ISSUE TITLE
Transfers - App - Add transfer_address to cancel transfer display

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#130]
Steps to reproduce:

- The sender should be able to see the transfer destination of a transferred ticket.
- Currently after a ticket was transferred the transferor is unable to see the destination of the transferred tickets.

**Comment by mrmaDrma** [comment]
What is suggestion to do this ?
Is there any UI ? Or you just want to add info modal here ?

**Comment by Tas4tari** [comment]
@mrmaDrma will add to this

**Comment by Tas4tari** [comment]
Tested in Beta on version 1.1.19 and works as expected. Tested in Prod and works as expected therefore closing this issue
