### ISSUE TITLE
User is unable to see all the events in the explore page after searching for an artist on iOS 

### ISSUE THREAD

**Issue by Anziskavds** [big-neon/bn-mobile-react#142]
Steps to reproduce:

- After a user searched for an artist and clicked on the artist name the user is unable to go back to the explore page to see the other events.
- It stays on that artist which was searched for.

**Comment by mrmaDrma** [comment]
@Anziskavds 
Please confirm me this:

If user searches for an artist, after clicking on that artist and going back to explore page, you want the search input to be blank and to display all events without search input ?

**Comment by Tas4tari** [comment]
@Anziskavds Please confirm expected behaviour

**Comment by Anziskavds** [comment]
@mrmaDrma That's correct yes. A user should be able to go back to the explore page and see all the events on there after they searched for an artist, event or location.

**Comment by Tas4tari** [comment]
Tested on IOS in Prod and works as expected. closing issue
