### ISSUE TITLE
When a ticket transfer is send to a existing user the transfer successful pop up notification does not appear on iOS

### ISSUE THREAD

**Issue by Anziskavds** [big-neon/bn-mobile-react#144]
Steps to reproduce:

- When a user transfers tickets to an existing user the "Transfer successful" pop up notification does not appear but it does when a ticket is being transferred to a new user. This is on iOS app.

**Comment by mrmaDrma** [comment]
I've just tested this on our iPhone 5. I transferred ticket from user doorperson@tari.com to superuser@test.com and modal popped without problem.

Can you tell me more, what model of iPhone you use, and please send me steps to reproduce, users you use etc.

**Comment by Tas4tari** [comment]
@mrmaDrma I think it was the ipod touch that was used @Anziskavds can you please confirm

**Comment by Anziskavds** [comment]
@mrmaDrma It was an iPad touch. 

Steps to reproduce: 
- Purchase a ticket
- Transfer the ticket to an existing Big Neon users email or contact number.
- No transfer successful pop up notification received after the transfer was done.

**Comment by mrmaDrma** [comment]
Hey there, I've tested this on simulator for iPad on our mac machine, since we don't have iPad for testing.
Regarding that, I was still able to see notification, which you can see on screenshoot I provided.
Are you sure you enabled notification permission on your device? Can you check that ?
![Screen Shot 2019-09-10 at 3 44 07 PM](https://user-images.githubusercontent.com/50660919/64619346-3a8e8880-d3e2-11e9-8b5b-3170e27a3bd5.png)

**Comment by mrmaDrma** [comment]
> Hey there, I've tested this on simulator for iPad on our mac machine, since we don't have iPad for testing.
> Regarding that, I was still able to see notification, which you can see on screenshoot I provided.
> Are you sure you enabled notification permission on your device? Can you check that ?
> ![Screen Shot 2019-09-10 at 3 44 07 PM](https://user-images.githubusercontent.com/50660919/64619346-3a8e8880-d3e2-11e9-8b5b-3170e27a3bd5.png)

**Comment by Tas4tari** [comment]
@Anziskavds Please confirm this

**Comment by Anziskavds** [comment]
@mrmaDrma Yes I am sure the notification permission is enabled. I have received it before before and I do receive it when it is being transferred to new user but not when it is transferred to an existing user. @Tas4tari

**Comment by Tas4tari** [comment]
@mrmaDrma Can you please confirm this still works when transferring to an existing user

**Comment by mrmaDrma** [comment]
> @mrmaDrma Can you please confirm this still works when transferring to an existing user

Well, as you can see from screenshot I've transfered it to superuser@test.com which is existing user on beta. I've tested it on simulator, today I will be able to test it on real iPad, then I will contact you when I get more information.

**Comment by Tas4tari** [comment]
@mrmaDrma  Once tested and verified on an iPad we will go from there

**Comment by Tas4tari** [comment]
@Anziskavds Can you please check this on Prod on IOS and see if this is still an issue

**Comment by Tas4tari** [comment]
Tested in Prod and works successfully. Issue is being closed
