### ISSUE TITLE
Ticket Transfer - If purchased more tickets of already reedeemed, redeemed tickets still visible for transfer, transfer not working

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#148]
STEPS TO REPRODUCE

1. Buy tickets to an event, redeem them 
2. Buy more tickets to same event
3. Attempt to transfer tickets

OUTCOME

1. All of the tickets (new and previously redeemed tickets) are available for ticket transfer
2. Unable to transfer new tickets (transfer button does not work)

**Comment by Tas4tari** [comment]
@simple-taskic  Can you please provide an estimate on this? We have a release date assigned as 17the September.
Please note that the estimates are based on days and not hours

**Comment by mrmaDrma** [comment]
@Tas4tari @Anziskavds 

Can you please provide me flow how to redeem ticket ?

**Comment by Anziskavds** [comment]
Scan / Redeem Tickets (Only via the app)

  As the user showing their QR code to be scanned:
    Login on your Big Neon app
    Click on "My Tickets" 
    Click on Event
    QR code shows for the ticket/s to be scanned
    Scan QR code
    Ticket scanned
    Scan ticket again (Should fail)
    Ticket scanned successfully 
    Customer is checked in successfully

As the Door Person:
Login on your Big Neon app
Click on "Account"
Click on Doorperson
Click on the Event
Click on scan tickets to scan the tickets to redeem or click on guest list and look/search for the customers name click on the name and click on complete check-in
