### ISSUE TITLE
Create 2 channel ID's

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#162]
Create the following 2 ID's:

1. 'event-messages'
2. 'transfers'

Supporting documentation:
https://docs.expo.io/versions/v34.0.0/guides/notification-channels/

**Comment by Tas4tari** [comment]
@coka This is for push notifications if I remember correctly

**Comment by coka** [comment]
@Tas4tari Correct. This is covered by #166.

**Comment by Tas4tari** [comment]
@coka Is this in Beta on version 1.1.19? If so any idea on how I can check this

**Comment by coka** [comment]
@Tas4tari Notification channels are a feature of Android 8.0 and above, so you will need to check this on a relatively recent Android phone. These two notification channels should be listed in the notification settings of the application, as shown [here](https://user-images.githubusercontent.com/10366797/66383487-625f1500-e9bd-11e9-8d2e-2c320c62f6bc.png) (the difference being that in Prod it won't be under "Expo", but under "Big Neon").

Note that this task is defined and completed in such a way that it adds no business value whatsoever. Notifying users through these notifications is a separate piece of work.

**Comment by Tas4tari** [comment]
@coka Thank you for letting me know.
