### ISSUE TITLE
App becomes unusable while browsing tickets

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-mobile-react#50]
Steps to reproduce
* Open the app
* Sign in as super user
* Go to My Tickets
* Choose "Simple Event"
* @Scroll through about 10 of the tickets, once you hit the 10th odd the app slows to a crawl

**Comment by Tas4tari** [comment]
@simple-taskic What is the progress on this?

**Comment by novi-kolacic** [comment]
Hey @Tas4tari well I have implemented everything that I thought it will improve the rendering.

**Comment by Tas4tari** [comment]
Duplicate issue, therefore closing
