### ISSUE TITLE
Launching App: User receives blank white screen.

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#58]
When I download the Big Neon Android App from the Play-store and launch for the first time, I receive a blank white screen.

![Screenshot_2019-05-30-12-02-02](https://user-images.githubusercontent.com/50987039/58625886-afc2cb80-82d3-11e9-88c5-e84e3877b4b4.png)

**Comment by mileTadic1994** [comment]
I've tried to reproduce this couple times yesterday, and few times today. Also I tested this on three different devices and couldn't reproduce this...

**Comment by simple-taskic** [comment]
Hey @mileTadic1994 I can see that @Tas4tari was on mobile data (not wifi) when he experienced this issue. Please, can you make sure that you have mobile data on, with possible low network signal?

**Comment by mileTadic1994** [comment]
> Hey @mileTadic1994 I can see that @Tas4tari was on mobile data (not wifi) when he experienced this issue. Please, can you make sure that you have mobile data on, with possible low network signal?

Still works for me. With wifi and mobile data.

**Comment by Tas4tari** [comment]
@mileTadic1994 I have uninstalled and reinstalled once again, also unable to reproduce, will close for now
