### ISSUE TITLE
Cannot open Payment Information view 

### ISSUE THREAD

**Issue by mileTadic1994** [big-neon/bn-mobile-react#65]
I'm not sure if you are aware of this. 
But first time when I opened view for payment information, it worked fined.
But now after I entered information and opened it again, I get blank page.

**Comment by simple-taskic** [comment]
Hey @Krakaw, please can you confirm if we need to fix this one? Thanks.

**Comment by Krakaw** [comment]
Can we get a cloudapp video of this bug please.

**Comment by Tas4tari** [comment]
@simple-taskic Could you please try again and if it is prevalent, I think we should go ahead and fix the issue

**Comment by mileTadic1994** [comment]
Sorry, I've made video, but forgot to upload it
[2019_06_07_10_47_33.mp4.tar.gz](https://github.com/big-neon/bn-mobile-react/files/3271195/2019_06_07_10_47_33.mp4.tar.gz)

.

**Comment by mileTadic1994** [comment]
@Krakaw @Tas4tari 
Sorry about this guys, looks like this was on my local branch where I did Event redesign.
Now its fixed, so I think we can close this.
