### ISSUE TITLE
Live Bug: Transferring ticket screen: Ticket ID not displayed within the text box correctly

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#71]
As a user when I want to transfer a ticket, I find that the Ticket ID displayed within the options is not displayed correctly as it transcends the text box it is displayed within. Because the Ticket ID is so long, it is not restricted to displaying within the text-box.

Expected Result:
Could you please only display the last 8 characters of the the Ticket ID

![image](https://user-images.githubusercontent.com/50987039/59182876-24ff8d80-8b6b-11e9-858a-c83cc6bfa48b.png)

**Comment by mileTadic1994** [comment]
@Tas4tari @Krakaw 
I accidentally pushed those changes directly on develop. I've fixed issue and tested it, so I think we wont have problem.
But maybe we should lock develop and master branch so we don't have this issues again?

**Comment by Krakaw** [comment]
There is an issue with the commit: https://github.com/big-neon/bn-mobile-react/commit/699f70c7c3756d2a8109871854fbfa29dc5b8274#commitcomment-33871111

I have locked the branches.
