### ISSUE TITLE
Element type is invalid: expected a string

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#75]
https://sentry.io/organizations/big-neon-5x/issues/1053354917/?project=1407235&query=is%3Aunresolved&statsPeriod=14d
Check the render method of AuthIndex

**Comment by mileTadic1994** [comment]
Can you provide me with more info about this. Because when I try to access this link it redirects me to login every time, even after I login.

**Comment by Krakaw** [comment]
Closing until we can reproduce
