### ISSUE TITLE
Missing Tickets from Location Selector

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#76]
Tickets that should show up in "California" location selection don't appear. We have multiple tickets in "San Francisco, California" that don't appear when switching from "San Francisco" as the location to "California" as the location
[big-neon-location-missing-tickets-trimmed.mp4.zip](https://github.com/revelrylabs/bn-mobile-react/files/3237914/big-neon-location-missing-tickets-trimmed.mp4.zip)
**Device:** Samsung S7 Edge, Android 8.0
**Steps to Reproduce**
 In Beta app
Select "California" as location
See no events listed
Select "San Francisco" as location
See lots of events listed

**Comment by mileTadic1994** [comment]
@Tas4tari @Krakaw 
Can you confirm this issue still doesn't work, I've tested it and it shows me events.
However, this also looks like problem with API, since with every filter we do API call.

**Comment by Krakaw** [comment]
This can be closed, only events linked to a region will show up. So if there are no events linked to that region, then none will show up.
