### ISSUE TITLE
Top Padding of Upcoming Tickets is Off / Can't Tap "X"

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#78]
**Description:** 
When viewing my Upcoming tickets, the view is overrun at the top of the screen by my notification bar. It overlaps with the "X" to close / return to the tickets index. This isn't the case on Past tickets.
**Upcoming** (see top left corner)
[Screenshot_20190523-171251_Big Neon] 
(https://user-images.githubusercontent.com/10236515/58290304-e8681f80-7d7e-11e9-9b78-5b210f232a49.jpg)
**Past**
[Screenshot_20190523-171327_Big Neon]
(https://user-images.githubusercontent.com/10236515/58290320-f453e180-7d7e-11e9-862b-70057fecdaf1.jpg)
 *found on iOS iPhone 7+
found on OSX High Sierra Chrome version 37.1*=
Platform: Android 8.0 [ ] Device: Samsung S7 Edge

**Comment by mileTadic1994** [comment]
@Tas4tari 
I've tested this on **iPhone 7+**, and those are screens for
**Upcomming**
![Simulator Screen Shot - iPhone 7 Plus - 2019-06-25 at 14 32 50](https://user-images.githubusercontent.com/50660919/60099487-077c1780-9758-11e9-859b-adbaf1e5e947.png)
![Simulator Screen Shot - iPhone 7 Plus - 2019-06-25 at 14 32 03](https://user-images.githubusercontent.com/50660919/60099488-0814ae00-9758-11e9-84e8-e97de256cc73.png)
![Simulator Screen Shot - iPhone 7 Plus - 2019-06-25 at 14 31 16](https://user-images.githubusercontent.com/50660919/60099489-0814ae00-9758-11e9-919d-6d06feddb80c.png)
**Past**
![Uploading Simulator Screen Shot - iPhone 7 Plus - 2019-06-25 at 14.32.30.png…]()

**Comment by mileTadic1994** [comment]
And those are screenshots of **Samsung S7 Edge**
**Upcomming**
![Screenshot_20190625-145215_Expo](https://user-images.githubusercontent.com/50660919/60100389-f0d6c000-9759-11e9-97ae-7129bb4bb6a0.jpg)
![Screenshot_20190625-145322_Expo](https://user-images.githubusercontent.com/50660919/60100390-f16f5680-9759-11e9-99ac-dca90be6bd0b.jpg)
**Past**
![Screenshot_20190625-145332_Expo](https://user-images.githubusercontent.com/50660919/60100434-051abd00-975a-11e9-8db2-71b103e0419e.jpg)

**Comment by mileTadic1994** [comment]
Maybe we could add greater top padding here, but it varies from event to event. If we add greater padding, it will look weird on bigger screens.
Also styles for this page is done really weird and it's confusing, I would like to do this from scratch once, if possible. 
Anyway, for now lets talk about solution for this issue particular. Do you want me to add padding, or is this okay to you ?

**Comment by Krakaw** [comment]
Adjust based on device screen size.
