### ISSUE TITLE
Cancel / `X` is cut off on right edge of Guest List list items

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#80]
Probably a design task BUT might not necessarily need a designer. I'm assuming this can be handled through some straight-forward style update(s).\r\n\r\n!
[Screenshot_20190522-151233_Big Neon]
(https://user-images.githubusercontent.com/10236515/58207309-0b73d000-7ca8-11e9-987b-2006652bb703.jpg)
**Steps to Reproduce**
Doorperson
Event > Check-in > Guest List
See that the `X` icon to the right of each guest/ticket is cut off on the edge of my screen
Probably worth testing this on an iOS device and/or another Android device that doesn't have an edge-to-edge display
Device Details: Samsung S7 Edge Android 8.0

**Comment by mileTadic1994** [comment]
@Tas4tari 
Well, we could maybe make smaller padding between items here. On that way the `>` icon (its not `x`) would show back again.

What do you think ?

**Comment by Krakaw** [comment]
Let's try, if it works then it is a good solution.

**Comment by mileTadic1994** [comment]
> Let's try, if it works then it is a good solution.

@Krakaw 
First one is from my mobile, Samsung J6.
And second one is from emulator with dimensions of Galaxy S7 Edge

![Screenshot_20190621-154401_Expo](https://user-images.githubusercontent.com/50660919/59928489-28362b80-943f-11e9-86a7-c1ec8bae742a.jpg)
![Screen Shot 2019-06-21 at 16 04 54](https://user-images.githubusercontent.com/50660919/59928498-2d937600-943f-11e9-88ff-a0eae52291ee.png)

**Comment by Tas4tari** [comment]
Tested on Beta version 1.1.19, Guest-list and on IOS in Prod works ass expected and there fore closing the issue
