### ISSUE TITLE
UX/UI - Event Listings - sold out events

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-mobile-react#85]
**Background**
Currently, users can view events, tap to navigate to a specific event details page, tap to purchase tickets for that event AND THEN can see that the event is completely sold out.
We should surface this information sooner in the workflow to avoid user frustration.
**Proposed enhancements:**
add a 'sold out' badge to sold out events on the listing view and the event details view
allow users to toggle on/off viewing sold out events

**Comment by mileTadic1994** [comment]
This issue could also be related to [Event Details redesign](https://github.com/big-neon/bn-mobile-react/issues/56)

**Comment by mileTadic1994** [comment]
@Krakaw @Tas4tari 
I'm gonna need override_status property  in response of getEvents in order to display badge.

**Comment by Krakaw** [comment]
@mileTadic1994 in the event view you can loop through the `ticket_types` array if there is 0 quantity available the show is sold out.

**Comment by mileTadic1994** [comment]
@Krakaw 
There is neither ticket_types property in this object.

**Comment by Krakaw** [comment]
@mileTadic1994 in the list use the min and max ticket price fields, in the event view you can use the ticket_types property

**Comment by mileTadic1994** [comment]
Object {
    "additional_info": null,
    "age_limit": "21",
    "artists": Array [
      Object {
        "artist": Object {
          "bandcamp_username": null,
          "bio": "",
          "created_at": "2019-05-07T08:38:02.454207",
          "facebook_username": null,
          "id": "0bd7343e-4f19-4b08-bd33-6cab0cc5f388",
          "image_url": "https://i.scdn.co/image/027610180dffa72f13c3527b3f50c2990c6325bf",
          "instagram_username": null,
          "is_private": true,
          "name": "Rainbow Kitten Surprise",
          "organization_id": "083f6feb-83b5-452c-af76-a3cf6dc25040",
          "other_image_urls": Array [
            "https://i.scdn.co/image/027610180dffa72f13c3527b3f50c2990c6325bf",
            "https://i.scdn.co/image/aebc97797d00ac654f9fbf540ba16c461df59edb",
            "https://i.scdn.co/image/8880c26761af4a126540276a04eda95e682833d8",
          ],
          "snapchat_username": null,
          "soundcloud_username": null,
          "spotify_id": "4hz8tIajF2INpgM0qzPJz2",
          "thumb_image_url": "https://i.scdn.co/image/8880c26761af4a126540276a04eda95e682833d8",
          "updated_at": "2019-05-07T08:38:02.454207",
          "website_url": null,
          "youtube_video_urls": Array [],
        },
        "event_id": "ab15c5aa-b142-4264-90f1-8dbc61d4969f",
        "importance": 0,
        "rank": 0,
        "set_time": "2019-05-08T03:00:00",
        "stage_id": null,
      },
      Object {
        "artist": Object {
          "bandcamp_username": null,
          "bio": "",
          "created_at": "2019-05-07T08:42:02.466929",
          "facebook_username": null,
          "id": "b32b4c5a-7c4f-4f76-95b1-4081d80bdd1f",
          "image_url": "https://i.scdn.co/image/e4fcad595ca988964cf6b56380b0224a8c0fecb3",
          "instagram_username": null,
          "is_private": true,
          "name": "Foxing",
          "organization_id": "083f6feb-83b5-452c-af76-a3cf6dc25040",
          "other_image_urls": Array [
            "https://i.scdn.co/image/e4fcad595ca988964cf6b56380b0224a8c0fecb3",
            "https://i.scdn.co/image/f1a4dc053b9417d1db3808607dd39adca7c8d764",
            "https://i.scdn.co/image/da4b3c6e72e473c70e9733ce6fb37d1b08758ddf",
          ],
          "snapchat_username": null,
          "soundcloud_username": null,
          "spotify_id": "2dfxY7YDuYCUtWFzWTS6IR",
          "thumb_image_url": "https://i.scdn.co/image/da4b3c6e72e473c70e9733ce6fb37d1b08758ddf",
          "updated_at": "2019-05-07T08:42:02.466929",
          "website_url": null,
          "youtube_video_urls": Array [],
        },
        "event_id": "ab15c5aa-b142-4264-90f1-8dbc61d4969f",
        "importance": 1,
        "rank": 1,
        "set_time": "2019-05-08T02:00:00",
        "stage_id": null,
      },
    ],
    "cancelled_at": null,
    "created_at": "2019-05-07T08:47:10.236212",
    "door_time": "2019-07-01T00:30:00",
    "event_end": "2019-07-02T05:00:00",
    "event_start": "2019-07-01T01:00:00",
    "event_type": "Music",
    "external_url": null,
    "id": "ab15c5aa-b142-4264-90f1-8dbc61d4969f",
    "is_external": false,
    "localized_times": Object {
      "door_time": "Mon,  1 Jul 2019 02:30:00 +0200",
      "event_end": "Tue,  2 Jul 2019 07:00:00 +0200",
      "event_start": "Mon,  1 Jul 2019 03:00:00 +0200",
    },
    "max_ticket_price": 2500,
    "min_ticket_price": 100,
    "name": "Rainbow Kitten Surprise",
    "organization_id": "083f6feb-83b5-452c-af76-a3cf6dc25040",
    "promo_image_url": "https://i.scdn.co/image/027610180dffa72f13c3527b3f50c2990c6325bf",
    "publish_date": "2019-05-07T08:47:39.006",
    "slug": "rainbow-kitten-surprise-39828",
    "status": "Published",
    "top_line_info": "cOME ONE Come aLL",
    "tracking_keys": Object {
      "facebook_pixel_key": null,
      "google_ga_key": null,
    },
    "updated_at": "2019-05-10T16:05:36.969827",
    "url": "https://beta.bigneon.com/events/rainbow-kitten-surprise-39828",
    "user_is_interested": false,
    "venue": Object {
      "address": "Public Works, Erie Street, San Francisco, CA, USA",
      "city": "San Francisco",
      "country": "United States",
      "created_at": "2019-05-03T15:09:15.755189",
      "google_place_id": null,
      "id": "39fb32a6-82f5-4d59-a901-0c8ac09734ad",
      "is_private": true,
      "latitude": 37.7688759,
      "longitude": -122.4194268,
      "name": "Big Neon ",
      "organization_id": "eb76a4f8-16f6-476b-9fdc-7e78fce98a73",
      "phone": "+ 0 (123) 456-7891",
      "postal_code": "94103",
      "promo_image_url": "https://res.cloudinary.com/dyro9cwim/image/upload/v1560330751/kjdov9nwx8s05ulk8qbs.jpg",
      "region_id": "7c893ede-8e0f-4c44-af01-b8c259a086cb",
      "state": "California",
      "timezone": "Africa/Johannesburg",
      "updated_at": "2019-06-20T11:05:29.455073",
    },
    "venue_id": "39fb32a6-82f5-4d59-a901-0c8ac09734ad",
  }

Anyway, here is one item from array that I've got. 
I'm not sure how can I know by min and max price that there are no tickets available?

**Comment by Tas4tari** [comment]
@Krakaw Could you please have a look at this

**Comment by Tas4tari** [comment]
@Krakaw @mileTadic1994 Chatted to @zmelamed about this yesterday, we will wait for designs to come through.
