### ISSUE TITLE
Upgrade bn-api-node to 2.0.9

### ISSUE THREAD

**Issue by Krakaw** [big-neon/bn-mobile-react#95]
Upgrade bn-api-node to 2.0.9 and test.

**Comment by simple-taskic** [comment]
Hey @Krakaw, I think that it's already done : https://github.com/big-neon/bn-mobile-react/blob/develop/package.json#L32

Should we close this one?

**Comment by Anziskavds** [comment]
Reviewed, we are currently on node 2.0.10
